version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:0.8.1-pg17-trixie
    container_name: postgres_pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgreadmin
      POSTGRES_DB: chatbot_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
